### ISSUE TITLE
Typos in Pool::put

### ISSUE THREAD

**Issue by Lezcano** [MoMEMta/MoMEMta#130]
This function leaks if `T`'s constructor throws when a new `std::shared_ptr<T>` is created. The correct code should be
`auto ptr = std::make_shared<T>(std::forward(args)...);`

Furthermore, I think that the correct signature of this function should make use of forwarding references,i.e.
`template <typename T, typename... Args> std::shared_ptr<T> Pool::put(const InputTag& tag, Args&&... args);`
(observe the `&&` added after `Args`)

I would make a pull request, but have never collaborated in any project, so I don't even know how to do them!! (how to properly test the program after having made the changes and so). If you could tell me how to collaborate I would not mind checking other parts of the code.

**Comment by blinkseb** [comment]
Thanks a lot for your feedback :+1: ! I''d be great if you can open a PR with the fixes, as you would be our first external contributor :tada: If you are new to git and github, the easiest is to fork our repository, create a new branch with your fixes, push it to your fork and then request a PR (see https://help.github.com/articles/creating-a-pull-request-from-a-fork/ for more details). You don't have to worry about the tests because we automatically run a bunch of checks and tests as soon as a PR is open :smiley:

If you don't feel comfortable with the process, we'll fix it on our side, but it can take a bit longer since we're all rather busy on other projects for the moment.

Thanks again!

**Comment by blinkseb** [comment]
Fixed by #131
